name = "fana"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Assets & Static Files
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Environment Variables (Non-sensitive)
[vars]
NODE_ENV = "production"

# Secrets yang harus diset via `wrangler secret put <NAMA_SECRET>`:
# - DATABASE_URL
# - TELEGRAM_BOT_TOKEN
# - ENCRYPTION_PEPPER
# - TELEGRAM_BOT_SECRET_TOKEN
